const $ = s => document.querySelector(s);
let personIndex = 0, contentIndex = 0, toastTimer, activePerson = null;
const profileFields = [['성명','예: 홍길동'],['출신지','예: 전라도'],['나이','예: 29세'],['키','예: 171cm'],['무게','예: 62kg']];
const personSeeds = [
 ['서윤, 31','전시 · 강아지 · 을지로','1534528741775-53994a69daeb'],['민준, 33','러닝 · 커피 · 독립영화','1500648767791-00dcc994a43e'],['지아, 29','여행 · 요가 · 사진','1517841905240-472988babdf9'],['도윤, 32','베이킹 · 야구 · 캠핑','1506794778202-cad84cf45f1d'],['하린, 30','서점 · LP · 와인','1508214751196-bcfd4ca60f91'],['윤아, 28','등산 · 드로잉 · 한강','1524504388940-b1c1722653e1'],['태호, 34','테니스 · 재즈 · 맛집','1507003211169-0a1dd7228f2d'],['수빈, 27','영화 · 비건 · 제주','1488426862026-3ee34a7d66df'],['현우, 35','사진 · 러닝 · 드라이브','1519085360753-af0119f7cbe7'],['나연, 32','뮤지컬 · 베이커리 · 산책','1529139574466-a303027c1d8b'],['준서, 30','보드게임 · 맥주 · 축구','1504593811423-6dd665756598'],['예린, 29','플라워 · 필라테스 · 바다','1529626455594-4ff0802cfb7e'],['시우, 31','서핑 · 커피 · 기타','1501196354995-cbb51c65aaea'],['다은, 33','공연 · 러닝 · 고양이','1512316609839-ce289d3eba0a'],['건우, 28','요리 · 자전거 · 전시','1502823403499-6ccfcf4fb453'],['유진, 30','클라이밍 · 만화 · 와인','1494790108377-be9c29b29330'],['재현, 36','여행 · 축구 · 캠핑','1507537297725-24a1c029d3ca'],['소희, 27','댄스 · 카페 · 사진','1506794778202-cad84cf45f1d'],['현지, 34','독서 · 러닝 · 재즈','1544005313-94ddf0286df2'],['지훈, 32','수영 · 요리 · 영화','1539571696357-5a69c17a67c6']
];
const people = personSeeds.map(([name,tags,id],i)=>({name,bio:['오늘의 기분을 나눌 수 있는 대화를 좋아해요.','좋아하는 장소를 함께 발견하고 싶어요.','천천히 오래 알아가는 만남을 기대해요.'][i%3],tags:tags.split(' · '),image:`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1800&q=88`}));
const contentSeeds = [
 ['ad','호텔에서 보내는 작은 휴식','오늘 예약 시 조식과 와인 혜택을 드려요.','1566073771259-6a8506099945'],['bookmark','연남동의 숨은 재즈 바','대화가 편안해지는 밤을 제안해요.','1514933651103-005eec06c04b'],['reel','퇴근 후의 한강','노을이 가장 예쁘던 7시 42분.','1492684223066-81342ee5ff30'],['comic','마주 앉기까지','오늘의 네 컷 이야기.','comic'],['ad','제주 숙소 주말 특가','두 사람을 위한 오션뷰 패키지.','1507525428034-b723cf961d3e'],['bookmark','이번 주말 전시','가볍게 시작하는 첫 만남 코스.','1549490349-8643362247b5'],['reel','새벽의 러닝 크루','같이 달리면 더 즐거운 강변.','1517836357463-d25dfeac3438'],['comic','답장을 기다리는 시간','조금 설레는 오후의 이야기.','comic'],['ad','성수 베이커리 한정 세트','커피 두 잔과 디저트를 한 번에.','1509440159596-0249088772ff'],['bookmark','을지로 레코드 숍','서로의 플레이리스트를 나눠봐요.','1483412033650-1015ddeb83d1'],['reel','주말 바다 산책','파도 소리와 함께한 짧은 영상.','1500530855697-b586d89ba3ee'],['comic','처음 건넨 인사','용기 내 보낸 한 마디.','comic'],['ad','도심 루프톱 영화제','이번 달 금요일, 야외 상영.','1489599849927-2ee91cede3ba'],['bookmark','망원동 브런치','느긋한 오전에 어울리는 식탁.','1495474472287-4d71bcdd2085'],['reel','비 오는 날의 플레이리스트','창밖의 비와 잘 어울리는 노래.','1516280440614-37939bbacd81'],['comic','우연한 재회','낯익은 뒷모습을 본 날.','comic'],['ad','한강 피크닉 세트','돗자리와 샌드위치가 준비돼요.','1473116763249-2faaef81ccda'],['bookmark','동네 책방의 밤','책과 맥주가 있는 작은 모임.','1507842217343-583bb7270b66'],['reel','골목길 사진 산책','오늘 발견한 가장 예쁜 빛.','1497366754035-f200968a6e72'],['comic','다음 약속','"그럼 다음에는 어디 갈까?"','comic']
];
const contents = contentSeeds.map(([kind,title,text,asset],i)=>({kind,title,text,asset,mark:kind==='ad'?'AD · 제안':kind==='bookmark'?'BOOKMARK · 추천':kind==='reel'?'REEL · 회원 영상':'COMIC · 회원 작품',image:asset==='comic'?null:`https://images.unsplash.com/photo-${asset}?auto=format&fit=crop&w=1800&q=88`,likes:12+i*3}));
const comments = [{name:'민지',text:'여기 분위기 정말 좋네요. 주말에 가보고 싶어요!',time:'3분 전'},{name:'도현',text:'저장해둡니다. 좋은 정보 감사합니다 :)',time:'12분 전'},{name:'서연',text:'사진만 봐도 기분이 좋아져요.',time:'28분 전'}];
const replies=['좋은 메시지네요! 저도 그렇게 생각했어요 :)','반가워요. 오늘은 어떤 하루였어요?','그 이야기 더 듣고 싶어요.','저도 좋아해요! 언제 한 번 이야기해요.'];
function pop(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2100)}
function renderFields(){const keys=[...document.querySelectorAll('.choice.selected')].map(x=>x.dataset.key);$('#inputs').innerHTML=keys.map(k=>`<div class="input-row"><label>${k}</label><input required placeholder="${profileFields.find(x=>x[0]===k)[1]}" /></div>`).join('')}
function closeSignup(){$('#onboarding').style.display='none';$('#experience').focus()}
function setupSignup(){const box=$('#choices');box.innerHTML=profileFields.map(([k])=>`<button class="choice" data-key="${k}" type="button">${k}</button>`).join('');[...box.children].slice(0,3).forEach(x=>x.classList.add('selected'));renderFields();box.onclick=e=>{const b=e.target.closest('.choice');if(!b)return;if(b.classList.contains('selected'))b.classList.remove('selected');else if(document.querySelectorAll('.choice.selected').length<3)b.classList.add('selected');else return pop('하나를 해제한 뒤 선택해주세요');renderFields()};$('#profileForm').onsubmit=e=>{e.preventDefault();if(document.querySelectorAll('.choice.selected').length!==3)return pop('세 가지를 선택해주세요');if([...$('#inputs').querySelectorAll('input')].some(x=>!x.value.trim()))return pop('선택한 정보를 모두 입력해주세요');localStorage.setItem('sbs-profile','done');closeSignup()};if(localStorage.getItem('sbs-profile'))closeSignup()}
function renderPerson(){const p=people[personIndex%people.length];activePerson=p;$('#screen').innerHTML=`<article class="profile-screen"><div class="visual" style="background-image:url('${p.image}')"></div><div class="profile-info"><span class="live">● 지금 접속 중</span><h2>${p.name}</h2><p>${p.bio}</p><div class="tags">${p.tags.map(t=>`<span>#${t}</span>`).join('')}</div></div><button class="love" aria-label="좋아요">♡</button></article>`;$('.love').onclick=e=>{e.currentTarget.classList.add('active');e.currentTarget.textContent='♥';activateChat(p);pop(`${p.name.split(',')[0]} 님과 매칭되었어요!`)}}
function renderContent(){const c=contents[contentIndex%contents.length];const social=`<div class="content-social"><button class="social-button like-content">♡ <span>${c.likes}</span></button><button class="social-button open-comments">💬 댓글 <span>${comments.length}</span></button></div>`;let body='';if(c.kind==='comic')body=`<article class="content-screen comic-screen"><div class="comic-panel">오늘, 시간 있어?</div><div class="comic-panel">좋아! 어디에서 볼까?</div><div class="comic-panel">조금 설레는 마음으로,</div><div class="comic-panel">다음 약속을 정했다.</div><div class="comic-social">${social}</div><p class="comic-caption">${c.mark} · ${c.title}</p></article>`;else body=`<article class="content-screen ${c.kind==='reel'?'reel-screen':''}"><div class="visual" ${c.kind==='reel'?'style="display:none"':`style="background-image:url('${c.image}')"`}></div>${c.kind==='bookmark'?'<button class="bookmark-icon">🔖</button>':''}<div class="content-info"><span class="ad-mark">${c.mark}</span><h2>${c.title}</h2><p>${c.text}</p>${social}</div></article>`;$('#screen').innerHTML=body;$('.like-content')?.addEventListener('click',e=>{e.currentTarget.classList.toggle('liked');e.currentTarget.innerHTML=e.currentTarget.classList.contains('liked')?`♥ <span>${c.likes+1}</span>`:`♡ <span>${c.likes}</span>`});$('.open-comments')?.addEventListener('click',openComments);$('.bookmark-icon')?.addEventListener('click',()=>pop('홈에 책갈피로 저장했어요'))}
function renderComments(){const list=$('#commentList');list.innerHTML=comments.map(c=>`<article class="comment"><b>${c.name}</b><p>${c.text}</p><small>${c.time}</small></article>`).join('');$('#commentCount').textContent=comments.length}
function openComments(){renderComments();$('#commentSheet').classList.remove('hidden');$('#commentInput').focus()}
function activateChat(p){$('#chatLaunch').classList.remove('hidden');$('#chatName').textContent=p.name.split(',')[0];$('#chatLog').innerHTML=`<div class="message them">매칭되었어요! 반가워요 :)</div><div class="message them">편하게 이야기해요.</div>`;$('#chatLaunch').onclick=()=>{$('#chatSheet').classList.remove('hidden');$('#chatInput').focus()}}
function cue(dir){const c=$(dir==='left'?'#cueLeft':'#cueRight');c.classList.remove('active');void c.offsetWidth;c.classList.add('active');$('#flash').classList.add('play');setTimeout(()=>{c.classList.remove('active');$('#flash').classList.remove('play')},430)}
function goLeft(){contentIndex++;renderContent();cue('left')}function goRight(){personIndex++;renderPerson();cue('right')}
window.addEventListener('keydown',e=>{if(getComputedStyle($('#onboarding')).display!=='none'||['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();goLeft()}if(e.key==='ArrowRight'){e.preventDefault();goRight()}},true);
$('#closeComments').onclick=()=>$('#commentSheet').classList.add('hidden');$('#closeChat').onclick=()=>$('#chatSheet').classList.add('hidden');$('#commentForm').onsubmit=e=>{e.preventDefault();const input=$('#commentInput');if(!input.value.trim())return;comments.unshift({name:'나',text:input.value.trim(),time:'방금 전'});input.value='';renderComments()};$('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;$('#chatLog').insertAdjacentHTML('beforeend',`<div class="message me">${text}</div>`);input.value='';$('#typing').classList.remove('hidden');setTimeout(()=>{const log=$('#chatLog');log.insertAdjacentHTML('beforeend',`<div class="message them">${replies[Math.floor(Math.random()*replies.length)]}</div>`);$('#typing').classList.add('hidden');log.scrollTop=log.scrollHeight},1000)};
$('#reset').onclick=()=>{localStorage.removeItem('sbs-profile');$('#onboarding').style.display='grid';renderFields();$('#chatLaunch').classList.add('hidden');$('#chatSheet').classList.add('hidden')};setupSignup();renderPerson();
