const $=s=>document.querySelector(s);let personIndex=0,contentIndex=0,toastTimer;
const profileFields=[['성명','예: 홍길동'],['출신지','예: 전라도'],['나이','예: 29세'],['키','예: 171cm'],['무게','예: 62kg']];
const people=[
  {name:'서윤, 31',bio:'낮에는 브랜드 디자이너, 밤에는 산책가예요. 마음이 가는 풍경을 함께 보고 싶어요.',tags:['전시','강아지','을지로'],image:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1800&q=88'},
  {name:'민준, 33',bio:'좋은 커피와 오래 걷는 대화를 좋아합니다. 다음 주말의 빈자리를 함께 채울래요?',tags:['러닝','커피','독립영화'],image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1800&q=88'},
  {name:'지아, 29',bio:'바다를 보러 훌쩍 떠나는 편이에요. 가장 좋아하는 계절은 여름의 끝.',tags:['여행','요가','사진'],image:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1800&q=88'}];
const contents=[
  {kind:'ad',mark:'AD · 오늘만',title:'성수의 작은 호텔,<br />20% 혜택',text:'도심 속 여유를 위한 한 밤. 조식과 와인 한 잔까지 함께해요.',button:'혜택 확인하고 예약하기 →',image:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1800&q=88'},
  {kind:'bookmark',mark:'BOOKMARK · 연남',title:'오늘 저녁, 이런 바<br />어때요?',text:'조용한 대화가 어울리는 연남동의 작은 바를 소개해요.',button:'추천 장소 보기 →',image:'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1800&q=88'},
  {kind:'reel',mark:'REEL · 현아 님',title:'퇴근 후의 한강',text:'노을이 가장 예쁘던 7시 42분. 오늘의 짧은 기록 ✨'},
  {kind:'comic',mark:'COMIC · 은비 작가',title:'마주 앉기까지',text:'오늘의 네 컷 이야기'}];
function pop(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2100)}
function renderFields(){const selected=[...document.querySelectorAll('.choice.selected')].map(b=>b.dataset.key);$('#inputs').innerHTML=selected.map(key=>{const option=profileFields.find(x=>x[0]===key);return `<div class="input-row"><label>${key}</label><input required aria-label="${key}" placeholder="${option[1]}" /></div>`}).join('')}
function setupSignup(){const box=$('#choices');box.innerHTML=profileFields.map(([key])=>`<button class="choice" data-key="${key}" type="button">${key}</button>`).join('');[...box.children].slice(0,3).forEach(b=>b.classList.add('selected'));renderFields();box.addEventListener('click',e=>{const button=e.target.closest('.choice');if(!button)return;const total=document.querySelectorAll('.choice.selected').length;if(button.classList.contains('selected'))button.classList.remove('selected');else{if(total===3){pop('하나를 해제한 뒤 새 항목을 선택해주세요');return}button.classList.add('selected')}renderFields()});$('#profileForm').addEventListener('submit',e=>{e.preventDefault();const selected=document.querySelectorAll('.choice.selected').length;if(selected!==3){pop('프로필 항목을 정확히 세 가지 선택해주세요');return}const values=[...$('#inputs').querySelectorAll('input')].map(i=>i.value.trim());if(values.some(v=>!v)){pop('선택한 세 가지를 모두 적어주세요');return}localStorage.setItem('sbs-profile',JSON.stringify(values));closeSignup();pop(`${values.join(' · ')} 님, 환영해요`)});if(localStorage.getItem('sbs-profile'))closeSignup()}
function closeSignup(){$('#onboarding').style.display='none';$('#experience').focus()}
function renderPerson(){const p=people[personIndex%people.length];$('#screen').innerHTML=`<article class="profile-screen"><div class="visual" style="background-image:url('${p.image}')"></div><div class="profile-info"><span class="live">● 지금 접속 중</span><h2>${p.name}</h2><p>${p.bio}</p><div class="tags">${p.tags.map(t=>`<span>#${t}</span>`).join('')}</div></div><button class="love" aria-label="좋아요">♡</button></article>`;$('.love').onclick=e=>{e.currentTarget.classList.toggle('active');e.currentTarget.textContent=e.currentTarget.classList.contains('active')?'♥':'♡';pop(e.currentTarget.classList.contains('active')?'마음에 담았어요':'좋아요를 취소했어요')}}
function renderContent(){const c=contents[contentIndex%contents.length];if(c.kind==='comic'){$('#screen').innerHTML=`<article class="content-screen comic-screen"><div class="comic-panel">"오늘, 시간 있어?"<br/>조심스레 보내 본 메시지.</div><div class="comic-panel">좋아!<br/>어디에서 볼까? ☺</div><div class="comic-panel">두 사람은 각자의 길을 나섰고,</div><div class="comic-panel">조금 설레는 마음으로<br/>서로를 기다렸다.</div><p class="comic-caption">${c.mark} · ${c.title}</p></article>`;return}const reel=c.kind==='reel';$('#screen').innerHTML=`<article class="content-screen ${reel?'reel-screen':''}"><div class="visual" ${reel?'style="display:none"':`style="background-image:url('${c.image}')"`}></div>${c.kind==='bookmark'?'<button class="bookmark-icon" aria-label="책갈피 저장">🔖</button>':''}<div class="content-info"><span class="ad-mark">${c.mark}</span><h2>${c.title}</h2><p>${c.text}</p><button class="action">${c.button||'♡ 24 · 댓글 6'}</button></div></article>`;const mark=$('.bookmark-icon');if(mark)mark.onclick=()=>pop('홈에 책갈피로 저장했어요');$('.action').onclick=()=>pop(reel?'좋아요를 남겼어요':'테스트 화면에서는 예약 화면을 열지 않아요')}
function cue(direction){const target=direction==='left'?$('#cueLeft'):$('#cueRight');target.classList.remove('active');void target.offsetWidth;target.classList.add('active');$('#flash').classList.add('play');setTimeout(()=>{$('#flash').classList.remove('play');target.classList.remove('active')},430)}
function goLeft(){contentIndex++;renderContent();cue('left')}
function goRight(){personIndex++;renderPerson();cue('right')}
window.addEventListener('keydown',e=>{if(getComputedStyle($('#onboarding')).display!=='none'||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();goLeft()}if(e.key==='ArrowRight'){e.preventDefault();goRight()}},true);
$('#reset').onclick=()=>{localStorage.removeItem('sbs-profile');$('#onboarding').style.display='grid';renderFields();pop('등록 정보를 초기화했어요')};setupSignup();renderPerson();
