const $ = (s) => document.querySelector(s);
const people = [
  ['서윤, 31','전시 · 강아지 · 을지로','1534528741775-53994a69daeb'],['민준, 33','러닝 · 커피 · 독립영화','1500648767791-00dcc994a43e'],['지아, 29','여행 · 요가 · 사진','1517841905240-472988babdf9'],['도윤, 32','베이킹 · 야구 · 캠핑','1506794778202-cad84cf45f1d'],['하린, 30','서점 · LP · 와인','1508214751196-bcfd4ca60f91'],['윤아, 28','등산 · 드로잉 · 한강','1524504388940-b1c1722653e1'],['태호, 34','테니스 · 재즈 · 맛집','1507003211169-0a1dd7228f2d'],['수빈, 27','영화 · 비건 · 제주','1488426862026-3ee34a7d66df'],['현우, 35','사진 · 러닝 · 드라이브','1519085360753-af0119f7cbe7'],['나연, 32','뮤지컬 · 베이커리 · 산책','1529139574466-a303027c1d8b'],['준서, 30','보드게임 · 맥주 · 축구','1504593811423-6dd665756598'],['예린, 29','플라워 · 필라테스 · 바다','1529626455594-4ff0802cfb7e'],['시우, 31','서핑 · 커피 · 기타','1501196354995-cbb51c65aaea'],['다은, 33','공연 · 러닝 · 고양이','1512316609839-ce289d3eba0a'],['건우, 28','요리 · 자전거 · 전시','1502823403499-6ccfcf4fb453'],['유진, 30','클라이밍 · 만화 · 와인','1494790108377-be9c29b29330'],['재현, 36','여행 · 축구 · 캠핑','1507537297725-24a1c029d3ca'],['소희, 27','댄스 · 카페 · 사진','1506794778202-cad84cf45f1d'],['현지, 34','독서 · 러닝 · 재즈','1544005313-94ddf0286df2'],['지훈, 32','수영 · 요리 · 영화','1539571696357-5a69c17a67c6']
].map(([name,tags,id],i)=>({name,tags:tags.split(' · '),note:['오늘의 기분을 함께 나눌 수 있는 대화를 좋아해요.','좋아하는 장소를 같이 발견하고 싶어요.','천천히 오래 알아가는 만남을 기대해요.'][i%3],image:`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=86`}));
const contentSeeds = [
  ['AD · TODAY','성수 작은 호텔','오늘 남은 더블룸 1실, 2인 45% 혜택','1566073771259-6a8506099945','호텔 특가'],['BOOKMARK','연남동 재즈 바','첫 만남에 어울리는 조용한 바를 저장해요.','1514933651103-005eec06c04b','장소 추천'],['REEL','퇴근 후의 한강','노을이 예쁘던 7시 42분의 짧은 기록.','1492684223066-81342ee5ff30','회원 영상'],['LOCAL PARTNER','망원 꽃집 클래스','2인 꽃다발 원데이 클래스, 오늘만 30% 할인','1490750967868-88aa4486c946','클래스'],['URGENT INVENTORY','영화관 잔여 연석','오늘 20:10, 중앙 블록 2자리를 특가로 열었어요.','1489599849927-2ee91cede3ba','영화 좌석'],['BOOKMARK','동네 책방의 밤','책과 맥주가 있는 작은 모임을 소개해요.','1507842217343-583bb7270b66','장소 추천'],['REEL','주말 바다 산책','파도 소리와 함께한 주말의 영상.','1500530855697-b586d89ba3ee','회원 영상'],['LOCAL PARTNER','성수 사진관','15분 미니 촬영과 보정 2장, 둘의 첫 기록.','1516035069371-29a1b244cc32','촬영'],['URGENT INVENTORY','이탈리안 바 창가','오늘 저녁 7시, 취소된 창가 2인석이에요.','1414235077428-338989a2e8c0','식당 예약'],['AD · TODAY','제주 오션뷰 숙소','주말 취소 객실 1실, 조식 포함 35% 혜택.','1507525428034-b723cf961d3e','호텔 특가'],['BOOKMARK','을지로 레코드 숍','서로의 플레이리스트를 나눠봐요.','1483412033650-1015ddeb83d1','장소 추천'],['REEL','새벽 러닝 크루','같이 달리면 더 즐거운 강변.','1517836357463-d25dfeac3438','회원 영상'],['LOCAL PARTNER','용산 도예 공방','머그컵을 함께 만드는 저녁 클래스.','1452860606245-08befc0ff44b','클래스'],['URGENT INVENTORY','프라이빗 상영관','오늘 밤 9시, 2시간 단독 대관이 비었어요.','1485846234645-a62644f84728','대관 예약'],['AD · TODAY','한강 피크닉 세트','돗자리와 샌드위치가 준비된 2인 세트.','1473116763249-2faaef81ccda','피크닉'],['BOOKMARK','망원 브런치','느긋한 오전에 어울리는 식탁.','1495474472287-4d71bcdd2085','장소 추천'],['REEL','비 오는 날 플레이리스트','창밖의 비와 잘 어울리는 노래.','1516280440614-37939bbacd81','회원 영상'],['LOCAL PARTNER','향수 공방','두 사람이 만드는 30ml 커스텀 향수.','1523293182086-7651a899d37f','클래스'],['URGENT INVENTORY','도예 공방 잔여석','오늘 저녁 클래스에 두 자리 남았어요.','1452860606245-08befc0ff44b','클래스'],['AD · TODAY','잠실 반려견 산책','주말 1시간 체험 산책을 시작해보세요.','1558788353-f76d92427f16','체험']
].map(([kind,title,body,id,booking],i)=>({kind,title,body,booking,likes:27+i*4,image:`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=86`}));
const fields=[['성명','예: 홍길동'],['출신지','예: 전라도'],['나이','예: 29세'],['키','예: 171cm'],['무게','예: 62kg']];
const comments=[{name:'민지',text:'여기 분위기 정말 좋네요. 주말에 가보고 싶어요!',time:'3분 전'},{name:'도현',text:'저장해둡니다. 좋은 정보 감사합니다 :)',time:'12분 전'},{name:'서연',text:'사진만 봐도 기분이 좋아져요.',time:'28분 전'}];
const onboardingStorageKey = 'sbs-sticky-onboarding-v2';
let mode='profile', personIndex=0, contentIndex=0, activeItem=null, toastTimer, drag=null;
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function render(){const item=mode==='profile'?people[personIndex%people.length]:contentSeeds[contentIndex%contentSeeds.length];activeItem=item;const next=mode==='profile'?people[(personIndex+1)%people.length]:contentSeeds[(contentIndex+1)%contentSeeds.length];$('#noteStack').innerHTML=`${noteMarkup(next,true)}${noteMarkup(item,false)}`;bindNoteActions()}
function noteMarkup(item,back){if(mode==='profile')return `<article class="sticky profile-note ${back?'back':''}"><span class="tape tape-top"></span><div class="polaroid"><img src="${item.image}" alt="${item.name}" /></div><p class="scribble">NEW CONNECTION</p><h1>${item.name}</h1><p class="note-body">${item.note}</p><div class="tag-row">${item.tags.map(t=>`<span>#${t}</span>`).join('')}</div><button class="heart" aria-label="좋아요">♡</button><button class="chat-chip">💬 매칭 후 채팅</button></article>`;return `<article class="sticky content-note ${back?'back':''}"><span class="tape tape-top"></span><div class="polaroid"><img src="${item.image}" alt="${item.title}" /></div><p class="scribble">${item.kind}</p><h1>${item.title}</h1><p class="note-body">${item.body}</p>${item.kind.includes('AD')||item.kind.includes('PARTNER')||item.kind.includes('INVENTORY')?`<button class="reserve">✦ AI로 ${item.booking} 예약</button>`:''}<div class="note-actions"><button class="like">♡ ${item.likes}</button><button class="comment">💬 ${comments.length}</button><button class="rate">★ 4.7</button></div></article>`}
function bindNoteActions(){const top=$('.sticky:not(.back)');top.querySelector('.heart')?.addEventListener('click',e=>{e.currentTarget.classList.add('selected');e.currentTarget.textContent='♥';openChat(activeItem.name.split(',')[0],['매칭되었어요! 반가워요 :)','편하게 이야기해요.'])});top.querySelector('.chat-chip')?.addEventListener('click',()=>toast('먼저 ♡를 눌러 매칭해보세요'));top.querySelector('.like')?.addEventListener('click',e=>{e.currentTarget.classList.toggle('selected');e.currentTarget.textContent=e.currentTarget.classList.contains('selected')?`♥ ${activeItem.likes+1}`:`♡ ${activeItem.likes}`});top.querySelector('.comment')?.addEventListener('click',openComments);top.querySelector('.rate')?.addEventListener('click',openRating);top.querySelector('.reserve')?.addEventListener('click',()=>openAgentChat(activeItem))}
function advance(which){mode=which;if(which==='profile')personIndex++;else contentIndex++;const top=$('.sticky:not(.back)');if(top){top.classList.add(which==='profile'?'exit-left':'exit-right');setTimeout(render,210)}else render();$('#gestureHint').classList.add('fade');setTimeout(()=>$('#gestureHint').classList.remove('fade'),500)}
function openSheet(id){$('#'+id).classList.remove('hidden')}function closeSheet(id){$('#'+id).classList.add('hidden')}
function openComments(){const list=$('#commentList');list.innerHTML=comments.map(c=>`<article><b>${c.name}</b><p>${c.text}</p><small>${c.time}</small></article>`).join('');$('#commentCount').textContent=comments.length;openSheet('commentSheet')}
function openRating(){$('#ratingTarget').textContent=activeItem.title;$('#ratingMessage').textContent='별점을 골라주세요.';$('#stars').querySelectorAll('button').forEach(x=>x.classList.remove('on'));openSheet('ratingSheet')}
function openChat(name,initial=[]){$('#chatName').textContent=name;$('#chatLog').innerHTML=initial.map(t=>`<div class="bubble them">${t}</div>`).join('');openSheet('chatSheet')}
function openAgentChat(item){openChat('AI 예약 도우미',[`${item.title} 예약을 확인하고 있어요.`,`남은 ${item.booking} 재고를 확인 중이에요.`]);$('#typing').classList.remove('hidden');setTimeout(()=>$('#chatLog').insertAdjacentHTML('beforeend',`<div class="bubble them">예약 정보를 전송했습니다.<br>테스트 사용자 · 2명</div>`),800);setTimeout(()=>$('#chatLog').insertAdjacentHTML('beforeend',`<div class="bubble them"><b>예약 완료 ✓</b><br>예약 번호 SBS-${Math.floor(100000+Math.random()*899999)}<br>테스트 결제수단으로 자동 확정</div>`),1650);setTimeout(()=>$('#typing').classList.add('hidden'),1700)}
function setupSignup(){const choices=$('#choices');choices.innerHTML=fields.map(([key])=>`<button type="button" data-key="${key}" aria-pressed="false">${key}</button>`).join('');[...choices.children].slice(0,3).forEach(x=>{x.classList.add('selected');x.setAttribute('aria-pressed','true')});renderSignupInputs();choices.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;e.preventDefault();const isSelected=b.classList.contains('selected');if(isSelected){b.classList.remove('selected');b.setAttribute('aria-pressed','false')}else if(choices.querySelectorAll('.selected').length<3){b.classList.add('selected');b.setAttribute('aria-pressed','true')}else{return toast('세 가지만 선택할 수 있어요')}renderSignupInputs()});$('#signupForm').addEventListener('submit',e=>{e.preventDefault();const values=[...$('#signupInputs input')].map(x=>x.value.trim());if(values.length!==3||values.some(x=>!x))return toast('선택한 세 가지를 모두 적어주세요');localStorage.setItem(onboardingStorageKey,JSON.stringify(values));$('#onboarding').classList.add('leave');setTimeout(()=>$('#onboarding').classList.add('hidden'),260)});if(localStorage.getItem(onboardingStorageKey))$('#onboarding').classList.add('hidden')}
function renderSignupInputs(){const selected=[...document.querySelectorAll('#choices .selected')].map(x=>x.dataset.key);$('#signupInputs').innerHTML=selected.map(k=>`<label>${k}<input placeholder="${fields.find(x=>x[0]===k)[1]}" required /></label>`).join('')}
function resetOnboarding(){localStorage.removeItem(onboardingStorageKey);$('#onboarding').classList.remove('hidden','leave')}
function setupMe(){const form=$('#meForm');const data=JSON.parse(localStorage.getItem('sbs-me')||'{}');Object.keys(data).forEach(k=>form.elements[k].value=data[k]);$('#meButton').onclick=()=>openSheet('meSheet');$('#reset').addEventListener('click',resetOnboarding);form.addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('sbs-me',JSON.stringify(Object.fromEntries(new FormData(form))));closeSheet('meSheet');toast('내 여행 취향을 저장했어요')})}
function setupDrag(){const stage=$('#stage');stage.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};stage.setPointerCapture?.(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x;const card=$('.sticky:not(.back)');if(card){card.style.transform=`translateX(${dx*.55}px) rotate(${dx*.025}deg)`;card.style.opacity=Math.max(.45,1-Math.abs(dx)/330)}});stage.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag=null;const card=$('.sticky:not(.back)');if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy))advance(dx>0?'content':'profile');else if(card){card.style.transform='';card.style.opacity=''}});stage.addEventListener('pointercancel',()=>{drag=null;const card=$('.sticky:not(.back)');if(card){card.style.transform='';card.style.opacity=''}})}
$('#contentButton').onclick=()=>advance('content');$('#profileButton').onclick=()=>advance('profile');$('#reset').onclick=()=>{localStorage.removeItem('sbs-profile');$('#onboarding').classList.remove('hidden','leave')};document.addEventListener('click',e=>{const close=e.target.dataset.close;if(close)closeSheet(close)});$('#commentForm').onsubmit=e=>{e.preventDefault();const input=$('#commentInput');if(!input.value.trim())return;comments.unshift({name:'나',text:input.value.trim(),time:'방금 전'});input.value='';openComments()};$('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput');if(!input.value.trim())return;$('#chatLog').insertAdjacentHTML('beforeend',`<div class="bubble me">${input.value.trim()}</div>`);input.value='';$('#typing').classList.remove('hidden');setTimeout(()=>{const replies=['좋은 이야기네요 :)','저도 그렇게 생각했어요.','더 듣고 싶어요!','오늘은 어떤 하루였어요?'];$('#chatLog').insertAdjacentHTML('beforeend',`<div class="bubble them">${replies[Math.floor(Math.random()*replies.length)]}</div>`);$('#typing').classList.add('hidden')},1000)};$('#stars').onclick=e=>{const b=e.target.closest('button');if(!b)return;const score=+b.dataset.score;$('#stars').querySelectorAll('button').forEach(x=>x.classList.toggle('on',+x.dataset.score<=score));$('#ratingMessage').textContent=`${score}점 평가가 등록됐어요. 고마워요!`;setTimeout(()=>closeSheet('ratingSheet'),800)};setupSignup();setupMe();setupDrag();render();
